# Generated by Django 3.0.7 on 2021-06-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noizedb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nlevel', models.IntegerField(verbose_name='Уровень шума')),
                ('location', models.IntegerField(verbose_name='Геолокация измерения')),
                ('Date', models.DateField(verbose_name='Дата проведения измерения')),
                ('Time', models.TimeField(verbose_name='Время проведения измерения')),
            ],
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='lat',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='lon',
            field=models.FloatField(verbose_name='Долгота'),
        ),
    ]
