# Generated by Django 3.0.7 on 2021-06-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noizedb', '0003_auto_20210605_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='User',
            field=models.CharField(default='Nobody', max_length=100, verbose_name='Имя пользователя'),
        ),
    ]
