# Generated by Django 3.0.7 on 2021-06-05 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noizedb', '0004_measurement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='User',
        ),
        migrations.AddField(
            model_name='measurement',
            name='Person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
