# Generated by Django 3.0.7 on 2021-06-07 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noizedb', '0006_auto_20210606_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='Nlevel',
            field=models.FloatField(verbose_name='Уровень шума'),
        ),
        migrations.CreateModel(
            name='Estimation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GenNlevel', models.FloatField(verbose_name='Обобщенный уровень шума')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noizedb.Coordinates')),
            ],
        ),
    ]
