# Generated by Django 3.0.7 on 2021-06-08 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noizedb', '0008_auto_20210607_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorChark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CharkParam', models.CharField(max_length=100, verbose_name='Характер источника шума')),
                ('CharkCor', models.FloatField(verbose_name='Значение коррекции по характеру источника шума')),
            ],
        ),
        migrations.CreateModel(
            name='CorFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FromParam', models.CharField(max_length=100, verbose_name='Происхождение шума')),
                ('FromCor', models.FloatField(verbose_name='Значение коррекции по происхожднию шума')),
            ],
        ),
        migrations.AddField(
            model_name='estimation',
            name='Color',
            field=models.CharField(max_length=50, null=True, verbose_name='Соответствующий цвет'),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='GenNlevel',
            field=models.FloatField(verbose_name='Оценочный уровень шума'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='Chark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noizedb.CorChark'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='From',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noizedb.CorFrom'),
        ),
    ]
